spring:
  application:
    name: eureka-server

server:
  port: 8761   # standard Eureka port

eureka:
  client:
    register-with-eureka: false   # server doesn't register itself
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0