spring:
  application:
    name: email-fetcher-service
  datasource:
    url: jdbc:mysql://localhost:3306/reachout_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8084

gemini:
  api-key: ${GEMINI_API_KEY}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent

job-service:
  url: http://localhost:8081
  user-token: ${USER_TOKEN}

email:
  poll-interval-ms: 300000  # poll every 5 minutes
  max-emails-per-poll: 10